version: '2'
services:
    imagerepublisher:
        build: .
        container_name: imagerepublisher
        environment:
            - "ROS_HOSTNAME=imagerepublisher"
            - "ROS_MASTER_URI=http://192.168.43.67:11311"
        command: rosrun image_transport republish compressed in:=/camera/image raw out:=/camera2

    balltracker:
        build: .
        container_name: balltracker
        depends_on:
            - "imagerepublisher"
        environment:
            - "DISPLAY"
            - "QT_X11_NO_MITSHM=1"
            - "ROS_HOSTNAME=balltracker"
            - "ROS_MASTER_URI=http://192.168.43.67:11311"
        volumes:
            - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
        command: python balltracker.py
